"""Symmetries of Cayley graphs and test-time augmentation."""

from functools import cached_property
from itertools import permutations
from typing import Optional, Sequence

import torch

from .cayley_graph_def import CayleyGraphDef
from .permutation_utils import is_permutation, inverse_permutation
from .predictor import Predictor
from .puzzles.moves import CUBE_222_ROTATIONS
from .torch_utils import CachedTensor


def _apply_then(p: Sequence[int], q: Sequence[int]) -> list[int]:
    """Returns permutation of positions equivalent to applying `p` to a state, and then applying `q`."""
    return [p[q[i]] for i in range(len(q))]


def _mean(tensors: list[torch.Tensor]) -> torch.Tensor:
    """Returns mean of given tensors of equal shape (converting integer tensors to floats)."""
    ans = torch.stack(tensors, dim=0)
    if not ans.is_floating_point():
        ans = ans.to(torch.float32)
    return ans.mean(dim=0)


def _conjugate(generator: Sequence[int], sigma: Sequence[int], sigma_inv: Sequence[int]) -> tuple[int, ...]:
    """Returns conjugate of `generator` by `sigma`, that is, permutation ``sigma^-1 * generator * sigma``."""
    return tuple(sigma_inv[generator[sigma[i]]] for i in range(len(sigma)))


def _derive_element_map(graph_def: CayleyGraphDef, sigma: list[int]) -> list[int]:
    """Returns relabeling of state elements induced by symmetry `sigma`.

    Symmetry moves element of the state at position ``sigma[i]`` to position ``i``, so for the central state to be
    preserved, element ``central_state[sigma[i]]`` must be relabeled to ``central_state[i]``. This defines the
    relabeling uniquely (elements that are not present in the central state are left as is).

    :param graph_def: Definition of the graph.
    :param sigma: Permutation of state positions defining the symmetry.
    :return: List where i-th element is what element `i` must be relabeled to.
    """
    central_state = graph_def.central_state
    ans: list[Optional[int]] = [None] * (max(central_state) + 1)
    for i, sigma_i in enumerate(sigma):
        src, dst = central_state[sigma_i], central_state[i]
        if ans[src] is None:
            ans[src] = dst
        elif ans[src] != dst:
            raise ValueError(
                f"Permutation {sigma} is not a symmetry: it does not preserve the central state (element {src} "
                f"would have to be relabeled to {ans[src]} and to {dst} at the same time)."
            )
    element_map = [x if x is not None else i for i, x in enumerate(ans)]
    if not is_permutation(element_map):
        raise ValueError(f"Permutation {sigma} is not a symmetry: induced relabeling {element_map} is not bijective.")
    return element_map


def _derive_action_map(graph_def: CayleyGraphDef, sigma: list[int]) -> list[int]:
    """Returns permutation of generators induced by symmetry `sigma`.

    Conjugate of every generator by `sigma` must again be a generator, and generators must be permuted bijectively.

    :param graph_def: Definition of the graph.
    :param sigma: Permutation of state positions defining the symmetry.
    :return: List where i-th element is index of the generator that conjugate of generator `i` is equal to.
    """
    generators = graph_def.generators_permutations
    generator_index = {tuple(g): i for i, g in enumerate(generators)}
    sigma_inv = inverse_permutation(sigma)
    ans = []
    for i, generator in enumerate(generators):
        conjugate = _conjugate(generator, sigma, sigma_inv)
        if conjugate not in generator_index:
            raise ValueError(
                f"Permutation {sigma} is not a symmetry: conjugate of generator "
                f"{graph_def.generator_names[i]} by it is not a generator."
            )
        ans.append(generator_index[conjugate])
    if not is_permutation(ans):
        raise ValueError(f"Permutation {sigma} is not a symmetry: it does not permute generators bijectively.")
    return ans


def _check_permutation_group(graph_def: CayleyGraphDef) -> None:
    if not graph_def.is_permutation_group():
        raise ValueError("Symmetries are supported only for graphs whose generators are permutations.")


def _is_symmetry(graph_def: CayleyGraphDef, sigma: list[int]) -> bool:
    """Whether permutation of state positions `sigma` is a symmetry of the graph."""
    try:
        _derive_element_map(graph_def, sigma)
        _derive_action_map(graph_def, sigma)
        return True
    except ValueError:
        return False


def _closure(graph_def: CayleyGraphDef, symmetries: list[list[int]]) -> list[list[int]]:
    """Returns the group generated by given symmetries (which is finite because it is a subgroup of S_n)."""
    identity = list(range(graph_def.state_size))
    ans = [identity]
    seen = {tuple(identity)}
    frontier = [identity]
    while frontier:
        new_frontier = []
        for element in frontier:
            for sigma in symmetries:
                product = _apply_then(element, sigma)
                if tuple(product) not in seen:
                    seen.add(tuple(product))
                    ans.append(product)
                    new_frontier.append(product)
        frontier = new_frontier
    return ans


class SymmetryGroup:
    """Group of symmetries of a Cayley graph (or a Schreier coset graph).

    Symmetry is defined by a permutation ``sigma`` of state positions. It maps state ``s`` to state ``T(s)`` where
    ``T(s)[i] = element_map[s[sigma[i]]]``, and ``element_map`` is the relabeling of state elements induced by `sigma`
    (see the :attr:`element_maps` property). For a graph where the central state is a permutation itself, `element_map`
    is inverse of `sigma`, so ``T`` is conjugation by `sigma`. For puzzles where elements of the state are colors,
    `element_map` is the permutation of colors: for example, rotating the whole 2x2x2 cube also permutes its faces.

    For this to be a symmetry (that is, a graph automorphism fixing the central state), two conditions are required:

      * ``T`` preserves the central state;
      * conjugate of every generator by `sigma` is again a generator.

    Then ``T`` preserves distances from the central state, and it maps children of ``s`` to children of ``T(s)``
    (with generators permuted, see :meth:`transport_actions`). This is used for test-time augmentation
    (see :class:`SymmetrizedPredictor`) and for deduplication of states equivalent under symmetries.

    Use :meth:`verify` to check that given permutations indeed form a group of symmetries of the graph.
    """

    def __init__(self, symmetries: list[list[int]], graph_def: CayleyGraphDef):
        """Initializes SymmetryGroup.

        :param symmetries: Symmetries, each being a permutation of `graph_def.state_size` positions.
        :param graph_def: Definition of the graph whose symmetries these are.
        """
        _check_permutation_group(graph_def)
        if len(symmetries) == 0:
            raise ValueError("At least one symmetry (e.g. the identity permutation) is required.")
        n = graph_def.state_size
        for sigma in symmetries:
            if len(sigma) != n or not is_permutation(sigma):
                raise ValueError(f"{sigma} is not a permutation of {n} positions.")
        if len({tuple(sigma) for sigma in symmetries}) != len(symmetries):
            raise ValueError("Symmetries must be distinct.")
        self.graph_def = graph_def
        self.symmetries = symmetries
        self.state_size = n
        self.n_symmetries = len(symmetries)
        self._verified = False

    @cached_property
    def element_maps(self) -> list[list[int]]:
        """Relabelings of state elements induced by the symmetries."""
        return [_derive_element_map(self.graph_def, sigma) for sigma in self.symmetries]

    @cached_property
    def action_maps(self) -> list[list[int]]:
        """Permutations of generators induced by the symmetries (see :meth:`transport_actions`)."""
        return [_derive_action_map(self.graph_def, sigma) for sigma in self.symmetries]

    @cached_property
    def _sigma_tensors(self) -> list[CachedTensor]:
        return [CachedTensor(torch.tensor(sigma, dtype=torch.int64)) for sigma in self.symmetries]

    @cached_property
    def _element_map_tensors(self) -> list[CachedTensor]:
        return [CachedTensor(torch.tensor(m, dtype=torch.int64)) for m in self.element_maps]

    @cached_property
    def _action_map_tensors(self) -> list[CachedTensor]:
        return [CachedTensor(torch.tensor(m, dtype=torch.int64)) for m in self.action_maps]

    def _check_symmetry_id(self, symmetry_id: int):
        if not 0 <= symmetry_id < self.n_symmetries:
            raise ValueError(f"symmetry_id must be between 0 and {self.n_symmetries - 1}, got {symmetry_id}.")

    def apply(self, states: torch.Tensor, symmetry_id: int) -> torch.Tensor:
        """Applies given symmetry to given states.

        :param states: One state (1-D tensor) or multiple states (2-D tensor), in decoded representation.
        :param symmetry_id: Index of the symmetry to apply.
        :return: Images of `states` under this symmetry, in the same shape as `states`.
        """
        self._check_symmetry_id(symmetry_id)
        states = torch.as_tensor(states)
        if len(states.shape) not in (1, 2) or states.shape[-1] != self.state_size:
            raise ValueError(f"Expected states of size {self.state_size}, got shape {tuple(states.shape)}.")
        sigma = self._sigma_tensors[symmetry_id].to(states.device)
        element_map = self._element_map_tensors[symmetry_id].to(states.device)
        ans = element_map[states.reshape((-1, self.state_size))[:, sigma]]
        return ans.reshape(states.shape)

    def transport_actions(self, symmetry_id: int) -> list[int]:
        """Returns permutation of generators induced by given symmetry.

        If ``T`` is this symmetry, and ``s*g`` denotes application of generator `g` to state `s`, then
        ``T(s*g_i) == T(s)*g_j`` where ``j`` is i-th element of the answer.

        :param symmetry_id: Index of the symmetry.
        :return: List of `n_generators` generator indexes.
        """
        self._check_symmetry_id(symmetry_id)
        return self.action_maps[symmetry_id]

    def transport_scores(self, child_scores: torch.Tensor, symmetry_id: int) -> torch.Tensor:
        """Transports scores computed for children of symmetry images back to children of the original states.

        If ``child_scores[i, j]`` is the score for the state obtained by applying generator `j` to
        ``apply(states, symmetry_id)[i]``, then element ``[i, j]`` of the answer is the score for the state obtained by
        applying generator `j` to ``states[i]``.

        :param child_scores: Tensor of shape ``[n_states, n_generators]`` with scores for children of the images.
        :param symmetry_id: Index of the symmetry that was applied to the states.
        :return: Tensor of shape ``[n_states, n_generators]`` with scores reordered for the original states.
        """
        self._check_symmetry_id(symmetry_id)
        n_generators = self.graph_def.n_generators
        if len(child_scores.shape) != 2 or child_scores.shape[1] != n_generators:
            raise ValueError(
                f"Expected child scores of shape [n_states, {n_generators}], got {tuple(child_scores.shape)}."
            )
        action_map = self._action_map_tensors[symmetry_id].to(child_scores.device)
        return child_scores[:, action_map]

    def verify(self) -> None:
        """Checks that these permutations form a group of symmetries of the graph.

        Raises ValueError explaining the problem if they do not. The check costs `n_symmetries` squared compositions,
        so its result is remembered: calling this again on a group that passed it costs nothing.
        """
        if self._verified:
            return
        # These raise ValueError if some permutation does not preserve the central state or does not permute generators.
        _ = self.element_maps
        _ = self.action_maps
        known = {tuple(sigma) for sigma in self.symmetries}
        identity = tuple(range(self.state_size))
        if identity not in known:
            raise ValueError("Identity permutation must be one of the symmetries.")
        for sigma1 in self.symmetries:
            for sigma2 in self.symmetries:
                if tuple(_apply_then(sigma1, sigma2)) not in known:
                    raise ValueError(
                        f"Symmetries are not closed under composition: composition of {sigma1} and {sigma2} "
                        "is not one of the symmetries."
                    )
        self._verified = True

    @staticmethod
    def derive(graph_def: CayleyGraphDef, *, max_state_size: int = 8) -> "SymmetryGroup":
        """Finds all symmetries of given graph by brute force.

        This checks all `state_size` factorial permutations, so it is only usable for graphs with very small states.
        For larger graphs, use hardcoded symmetries (e.g. :meth:`rubik_cube_rotations`).

        :param graph_def: Definition of the graph.
        :param max_state_size: Maximal state size for which brute force is allowed.
        :return: SymmetryGroup with all symmetries of this graph.
        """
        _check_permutation_group(graph_def)
        n = graph_def.state_size
        if n > max_state_size:
            raise ValueError(
                f"Brute force is too slow for state size {n} (max_state_size={max_state_size}). Hardcode symmetries "
                "for this graph instead."
            )
        ans = [list(p) for p in permutations(range(n)) if _is_symmetry(graph_def, list(p))]
        return SymmetryGroup(ans, graph_def)

    @staticmethod
    def reflections(graph_def: CayleyGraphDef) -> "SymmetryGroup":
        """Returns symmetry group generated by reflections of state positions.

        Reflection with parameter `m` maps position `i` to position ``(m-i) mod n``. For graphs whose generators are
        cyclic shifts and a transposition (e.g. created by :meth:`cayleypy.PermutationGroups.lrx`), exactly one
        reflection is a symmetry: it swaps the two shifts and preserves the transposition.

        :param graph_def: Definition of the graph.
        :return: SymmetryGroup generated by all reflections that are symmetries of this graph.
        """
        n = graph_def.state_size
        identity = list(range(n))
        candidates = [[(m - i) % n for i in range(n)] for m in range(n)]
        found = [sigma for sigma in candidates if sigma != identity and _is_symmetry(graph_def, sigma)]
        if len(found) == 0:
            raise ValueError("No reflection of state positions is a symmetry of this graph.")
        ans = SymmetryGroup(_closure(graph_def, found), graph_def)
        ans.verify()
        return ans

    @staticmethod
    def rubik_cube_rotations(graph_def: CayleyGraphDef) -> "SymmetryGroup":
        """Returns symmetry group of 24 rotations of the whole 2x2x2 Rubik's cube.

        These rotations are symmetries for any metric of the 2x2x2 cube (e.g. graphs created by
        ``Puzzles.rubik_cube(2, metric="QTM")``), because rotating the whole cube turns a face turn into a face turn.

        :param graph_def: Definition of the graph for 2x2x2 Rubik's cube.
        :return: SymmetryGroup with the 24 rotations.
        """
        if graph_def.state_size != len(CUBE_222_ROTATIONS[0]):
            raise ValueError(
                f"Rotations are hardcoded only for the 2x2x2 cube (state size {len(CUBE_222_ROTATIONS[0])}), but this "
                f"graph has state size {graph_def.state_size}."
            )
        ans = SymmetryGroup([list(sigma) for sigma in CUBE_222_ROTATIONS], graph_def)
        ans.verify()
        return ans


class SymmetrizedPredictor(Predictor):
    """Predictor that averages predictions of another predictor over symmetries of the graph.

    This is test-time augmentation (TTA): because symmetries preserve distances from the central state, predictions for
    all images of a state are predictions for the same true distance, so averaging them reduces error of an imperfect
    model. Predictions of this predictor are symmetric by construction: they are equal for all states in one orbit
    (which is why the symmetries are verified to form a group, see :meth:`SymmetryGroup.verify`).

    The price is `n_symmetries` times more model evaluations.

    A `base` that scores children of a state instead of the state itself (a Q-model) is symmetrized through
    :meth:`score_children` only: like the model itself, it has nothing to say about a state, so :meth:`__call__` needs
    `base` to return one score per state.
    """

    def __init__(self, base: Predictor, symmetry_group: SymmetryGroup):
        """Initializes SymmetrizedPredictor.

        :param base: Predictor to symmetrize.
        :param symmetry_group: Symmetries of the graph to average over. Must be created for the same graph as `base`,
            and must really be a group of symmetries of it (:meth:`SymmetryGroup.verify` is called to check that).
        """
        base_def = base.graph.definition
        symmetries_def = symmetry_group.graph_def
        if (
            base_def.generators_permutations != symmetries_def.generators_permutations
            or base_def.central_state != symmetries_def.central_state
        ):
            raise ValueError("Symmetry group was created for a different graph than the base predictor.")
        # Averaging over a set that is not a group of symmetries gives predictions that are not symmetric, which is the
        # one thing this predictor promises - so the group is verified here instead of being trusted.
        symmetry_group.verify()
        self.base = base
        self.symmetry_group = symmetry_group
        super().__init__(base.graph, self._predict_symmetrized)
        # Symmetrizing a Q-model leaves it a Q-model: callers dispatch on this to score children instead of states.
        self.n_outputs = base.n_outputs

    def _predict_symmetrized(self, states: torch.Tensor) -> torch.Tensor:
        symmetries = range(self.symmetry_group.n_symmetries)
        return _mean([self.base(self.symmetry_group.apply(states, i)) for i in symmetries])

    def score_children(self, states: torch.Tensor) -> torch.Tensor:
        """Estimates distances from central state to all children of given states, averaging over symmetries.

        :param states: States (in decoded representation) whose children to score.
        :return: Tensor of shape ``[n_states, n_generators]`` with estimated distances for children.
        """
        scores = []
        for i in range(self.symmetry_group.n_symmetries):
            child_scores = self.base.score_children(self.symmetry_group.apply(states, i))
            scores.append(self.symmetry_group.transport_scores(child_scores, i))
        return _mean(scores)
