"""Trainer for models estimating distances in a Cayley graph."""

import copy
import math
import typing
import warnings
from dataclasses import dataclass, field
from typing import Optional, Sequence

import torch
from torch import nn

from .config import TrainConfig
from .data import BfsAnchors, DataSource, MixtureDataSource, RandomWalksSource, SparseQSampler, TrainingData
from ..models.checkpoint import PathType, load_checkpoint, save_checkpoint
from ..models.models import ModelConfig
from ..predictor import Predictor

if typing.TYPE_CHECKING:
    from ..cayley_graph import CayleyGraph


@dataclass
class TrainResult:
    """Result of training.

    :param losses: Mean loss on every epoch. Because data is regenerated on every epoch, these are losses on states
        the model has not seen before, so they can be read as a validation curve.
    :param n_steps: Total number of optimizer steps made.
    :param stage_losses: The same losses split by stage, for training run by :meth:`Trainer.train_stages`. A single
        stage leaves this with one element; where the boundaries are matters, because the loss usually jumps at one
        (the learning rate restarts, and with ``TrainConfig.targets="bellman"`` the targets change altogether).
    """

    losses: list[float]
    n_steps: int
    stage_losses: list[list[float]] = field(default_factory=list)


def _validate_model_config(model_config: ModelConfig, graph: "CayleyGraph") -> None:
    """Checks that a model described by this config can be trained for this graph."""
    state_size = graph.definition.state_size
    n_generators = graph.definition.n_generators
    if model_config.input_size != state_size:
        raise ValueError(
            f"Model expects states of size {model_config.input_size}, but states of this graph have size {state_size}."
        )
    if model_config.n_outputs not in (1, n_generators):
        raise ValueError(
            f"Model must have either one output (predicting the distance of a state) or one output per generator of "
            f"this graph, of which there are {n_generators} (predicting distances of all children of a state), got "
            f"n_outputs={model_config.n_outputs}."
        )
    # Models consuming tokenized states do not use one-hot encoding, so this only applies to the other ones.
    if model_config.tokenizer_groups is None:
        max_value = int(graph.central_state.max())
        if model_config.num_classes_for_one_hot <= max_value:
            raise ValueError(
                f"Model one-hot encodes states with {model_config.num_classes_for_one_hot} classes, which is not "
                f"enough for this graph, where an element of a state can be as large as {max_value}."
            )


def _warn_if_not_inverse_closed(graph: "CayleyGraph") -> None:
    """Warns that targets generated for this graph need not measure the distance a predictor is asked about."""
    if graph.definition.generators_inverse_closed:
        return
    warnings.warn(
        "Generators of this graph are not inverse closed, so the random walks used for training measure the distance "
        "from the central state, which need not be the distance to it - and a predictor is asked for the latter. To "
        "get targets in the direction a predictor is asked about, train on CayleyGraph.with_inverted_generators. This "
        "check looks at the generators alone, so it is a false alarm for a graph whose induced action on states is "
        "symmetric anyway.",
        stacklevel=3,
    )


class Trainer:
    """Trains a model to estimate distance from the central state of a Cayley graph.

    On every epoch, a fresh piece of training data is generated by a :class:`cayleypy.train.DataSource` described by the
    config: random walks, where the number of steps at which a state was visited is its target distance, optionally
    mixed with anchors - states whose exact distance is known from a breadth-first search around the central state
    (`TrainConfig.anchors_depth`). Walk targets are upper estimates of the true distance (see
    :class:`cayleypy.algo.RandomWalksGenerator`), which is why fast-mixing walks ("nbt") are the default.

    Both models with one output and Q-models (one output per generator) can be trained. For a Q-model, walk targets
    come from :class:`cayleypy.train.SparseQSampler` (only the moves along the walk are labeled) and anchors label all
    the outputs exactly. Data from any other source, e.g. paths found by a previous beam search
    (:class:`cayleypy.train.PathDataSource`), can be trained on by passing `data_source`.

    The model is fitted with AdamW, the learning rate follows a cosine schedule, and an exponential moving average
    (EMA) of the weights is maintained - it is usually a better predictor than the weights themselves, and it is what
    :meth:`predictor` and :meth:`save` use by default.

    Training progress is reported with `print` when `TrainConfig.verbose` is at least 1.

    Walks start at the central state, so what their targets measure is the distance from it, while a predictor is asked
    for the distance to it. These are the same distance when the generators of the graph are inverse closed, and the
    trainer warns when they are not.

    Example:

    >>> from cayleypy import CayleyGraph, PermutationGroups
    >>> from cayleypy.models import ModelConfig
    >>> from cayleypy.train import TrainConfig, Trainer
    >>> graph = CayleyGraph(PermutationGroups.lrx(4), device="cpu")
    >>> model_config = ModelConfig(model_type="MLP", input_size=4, num_classes_for_one_hot=4, layers_sizes=[16])
    >>> train_config = TrainConfig(n_epochs=2, n_walks=8, rw_length=4, batch_size=16, seed=0)
    >>> result = Trainer(graph, model_config, train_config).train()
    >>> len(result.losses)
    2
    """

    def __init__(
        self,
        graph: "CayleyGraph",
        model_config: ModelConfig,
        config: Optional[TrainConfig] = None,
        model: Optional[nn.Module] = None,
        data_source: Optional[DataSource] = None,
    ):
        """Initializes Trainer.

        :param graph: Graph for which to train the model.
        :param model_config: Config describing the model to train. It is also stored in checkpoints written by
            :meth:`save`, which makes them self-describing.
        :param config: Configuration of the training process. Defaults to `TrainConfig()`.
        :param model: Model to train (optional). Defaults to a model built from `model_config` with randomly
            initialized weights. Pass a model to continue training an existing one - it must be described by
            `model_config`.
        :param data_source: Where to get training data (optional). Defaults to the source described by `config` -
            random walks, with anchors mixed in if `TrainConfig.anchors_depth` is set. Pass a source to train on
            anything else, e.g. on paths found by beam search, or on a mixture including them.
        """
        _validate_model_config(model_config, graph)
        _warn_if_not_inverse_closed(graph)
        self.graph = graph
        self.model_config = model_config
        self.config = config if config is not None else TrainConfig()
        if self.config.seed is not None:
            torch.manual_seed(self.config.seed)
        self.model = (model_config.build_model() if model is None else model).to(graph.device)
        self.data_source = data_source if data_source is not None else self._make_data_source()
        self.loss = self.config.make_loss()
        self._reset_optimizer()
        self.ema_model: Optional[nn.Module] = None
        self._reconcile_ema()
        self.epoch = 0
        self.n_steps = 0

    @classmethod
    def from_checkpoint(
        cls,
        path: PathType,
        graph: "CayleyGraph",
        config: Optional[TrainConfig] = None,
    ) -> "Trainer":
        """Creates trainer continuing training of a model stored in a checkpoint.

        Only weights are stored in checkpoints, so the optimizer, the learning rate schedule and the EMA copy start
        anew (the EMA copy starts from the weights that were loaded).

        To fine-tune a pretrained model with another training scheme, pass a config with the `targets` of that
        scheme - or use :meth:`train_stages`, which keeps the model in memory instead of going through a file.

        :param path: Path to a checkpoint written by :func:`cayleypy.models.save_checkpoint` (e.g. by :meth:`save`).
        :param graph: Graph for which to continue training. If the checkpoint says which graph the model was trained
            for, it must be this graph.
        :param config: Configuration of the training process. Defaults to `TrainConfig()`.
        :return: The trainer.
        """
        model, model_config = load_checkpoint(path, device=str(graph.device), graph_def=graph.definition)
        return cls(graph, model_config, config=config, model=model)

    @property
    def learning_rate(self) -> float:
        """Learning rate that will be used on the next optimizer step."""
        return float(self.optimizer.param_groups[0]["lr"])

    def generate_data(self) -> TrainingData:
        """Generates training data for one epoch, using `data_source`.

        :return: States with their target distances.
        """
        return self.data_source.generate()

    def _make_data_source(self) -> DataSource:
        """Creates the data source described by the config."""
        config = self.config
        n_outputs = self.model_config.n_outputs
        if config.targets == "bellman":
            # Imported here and not at the top because bellman.py builds on this module's config: importing it
            # there would be circular.
            from .bellman import make_bellman_source  # pylint: disable=import-outside-toplevel

            return make_bellman_source(self.graph, config, self.model, n_outputs=n_outputs)
        walks: DataSource
        if n_outputs == 1:
            walks = RandomWalksSource(
                self.graph,
                n_walks=config.n_walks,
                rw_length=config.rw_length,
                mode=config.rw_mode,
                nbt_history_depth=config.nbt_history_depth,
            )
        else:
            walks = SparseQSampler(self.graph, n_walks=config.n_walks, rw_length=config.rw_length)
        if config.anchors_depth == 0:
            return walks
        # Anchors generate exactly their share of what the walks generate, so the mixture has little to throw away.
        fraction = config.anchors_fraction
        n_walk_states = config.n_walks * config.rw_length
        size = max(1, int(round(fraction / (1 - fraction) * n_walk_states)))
        anchors = BfsAnchors(self.graph, depth=config.anchors_depth, size=size, n_outputs=n_outputs)
        return MixtureDataSource([walks, anchors], [1 - fraction, fraction])

    def train_step(
        self,
        states: torch.Tensor,
        targets: torch.Tensor,
        mask: Optional[torch.Tensor] = None,
        weights: Optional[torch.Tensor] = None,
    ) -> float:
        """Makes one optimizer step on the given batch, then updates the EMA copy of the weights.

        :param states: States (in decoded representation) to train on.
        :param targets: Target distances for `states`.
        :param mask: Which targets are known (optional), see :class:`cayleypy.train.Loss`.
        :param weights: Importance of every target (optional), see :class:`cayleypy.train.Loss`.
        :return: Value of the loss on this batch, before the step.
        """
        self.model.train()
        self.optimizer.zero_grad(set_to_none=True)
        loss = self.loss(self.model(states), targets, mask=mask, weights=weights)
        loss.backward()
        self.optimizer.step()
        self.n_steps += 1
        self._update_ema()
        return float(loss.detach())

    def train_on_data(self, data: TrainingData) -> float:
        """Makes one pass over the given data, in batches of `TrainConfig.batch_size`.

        :param data: States with their target distances.
        :return: Mean loss over the batches of this pass.
        """
        n_states = len(data)
        if n_states == 0:
            raise ValueError("Cannot train on an empty set of states.")
        n_batches = int(math.ceil(n_states / self.config.batch_size))
        permutation = torch.randperm(n_states, device=data.states.device)
        losses = []
        for index in permutation.tensor_split(n_batches):
            batch = data.select(index)
            losses.append(self.train_step(batch.states, batch.targets, mask=batch.mask, weights=batch.weights))
        return sum(losses) / len(losses)

    def train_epoch(self) -> float:
        """Generates data for one epoch and makes one pass over it.

        The data source is told that an epoch is starting (:meth:`cayleypy.train.DataSource.on_epoch_start`) before
        the data is generated, which is how a source that reads the model being trained picks up its current weights.

        :return: Mean loss on this epoch.
        """
        learning_rate = self.learning_rate
        self.data_source.on_epoch_start(self)
        mean_loss = self.train_on_data(self.generate_data())
        self.scheduler.step()
        self.epoch += 1
        if self.config.verbose >= 1:
            print(f"Epoch {self.epoch}: loss={mean_loss:.5f}, lr={learning_rate:.3e}.")
        return mean_loss

    def train(self) -> TrainResult:
        """Trains the model for `TrainConfig.n_epochs` epochs.

        Calling this again continues training the same model, but the cosine schedule of the learning rate is built for
        one call, so on the second call the learning rate goes back up.

        :return: Result of training, with the loss curve.
        """
        losses = [self.train_epoch() for _ in range(self.config.n_epochs)]
        if self.config.verbose >= 1:
            print(f"Training finished in {self.n_steps} steps, loss on the last epoch: {losses[-1]:.5f}.")
        return TrainResult(losses=losses, n_steps=self.n_steps, stage_losses=[losses])

    def _validate_stage(self, config: TrainConfig) -> None:
        """Checks that a stage described by this config can be entered, without changing anything.

        :param config: Configuration of the stage.
        :raises ValueError: If the stage cannot be trained for this graph.
        """
        if config.targets == "bellman":
            # Imported here and not at the top because bellman.py builds on this module's config: importing it
            # there would be circular.
            from .bellman import check_bellman_graph  # pylint: disable=import-outside-toplevel

            check_bellman_graph(self.graph)

    def _reconcile_ema(self) -> None:
        """Makes the EMA copy match `TrainConfig.ema_decay` of the current config.

        A stage can turn averaging on or off, and the copy has to follow: switching it on starts a fresh copy from the
        weights the previous stage left, and switching it off drops the copy instead of leaving a stale one that
        :meth:`model_for_inference` would keep returning.
        """
        if self.config.ema_decay > 0:
            if self.ema_model is None:
                self.ema_model = copy.deepcopy(self.model).eval()
                for parameter in self.ema_model.parameters():
                    parameter.requires_grad_(False)
        else:
            self.ema_model = None

    def _reset_optimizer(self) -> None:
        """Creates the optimizer and the learning rate schedule described by the current config."""
        self.optimizer = torch.optim.AdamW(
            self.model.parameters(), lr=self.config.lr, weight_decay=self.config.weight_decay
        )
        self.scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            self.optimizer, T_max=self.config.n_epochs, eta_min=self.config.lr_min
        )

    def set_stage(self, config: TrainConfig, data_source: Optional[DataSource] = None) -> None:
        """Starts a new stage of training of the same model.

        The model and its EMA copy carry over; the optimizer, the learning rate schedule and the epoch counter are
        created anew, because a stage is a new training regime rather than a continuation of the previous one. This is
        the difference from calling :meth:`train` twice, which reuses the optimizer of the first call.

        The learning rate therefore jumps at a stage boundary - from `lr_min` of the previous config to `lr` of the
        new one. That jump is a hyperparameter of staged training, not an accident, so a large one is reported when
        `TrainConfig.verbose` is at least 1.

        Entering a stage is not atomic: what the previous stage held is released before the next one is built, because
        holding two sets of anchors or two optimizers at once is what makes a staged run run out of memory. Everything
        that can be checked in advance is (see :meth:`_validate_stage`), but a failure during construction - a
        breadth-first search that exceeds its limit, say - leaves the trainer unable to train, and it says so. The
        weights survive, so a new trainer can continue from them.

        :param config: Configuration of the new stage.
        :param data_source: Where to get training data in this stage (optional). Defaults to the source described by
            `config`, which is also how `TrainConfig.targets` takes effect. When one is given, `TrainConfig.targets` is
            ignored, and so is the check of what its scheme would need of the graph.
        :raises RuntimeError: If the stage could not be built after the previous one was released.
        """
        previous_lr = self.learning_rate
        # Checked before anything is mutated: a stage that cannot be entered must leave the trainer in the stage it is
        # in, rather than half-way into one with no data source to train on. A supplied source is used instead of the
        # scheme named by the config, so what that scheme would need of the graph does not apply.
        if data_source is None:
            self._validate_stage(config)
        self.config = config
        if config.seed is not None:
            torch.manual_seed(config.seed)
        self.loss = config.make_loss()
        # What the previous stage held is released before the next stage allocates. The optimizer keeps two moment
        # tensors per parameter, and building a source runs a breadth-first search when the stage uses anchors - so
        # holding both stages at once is what can make a staged run run out of memory, even though every stage fits.
        del self.optimizer, self.scheduler
        if config.ema_decay == 0:
            self.ema_model = None
        if data_source is None:
            del self.data_source
            try:
                self.data_source = self._make_data_source()
            except Exception as error:
                raise RuntimeError(
                    "Failed to enter the stage after the previous one was released, so this trainer cannot train any "
                    "more. Its weights are intact: build a new trainer with model=trainer.model_for_inference() and a "
                    "stage that fits. Releasing the previous stage first is deliberate - holding both at once is what "
                    "makes a staged run run out of memory - so entering a stage is not an atomic operation."
                ) from error
        else:
            self.data_source = data_source
        self._reset_optimizer()
        self._reconcile_ema()
        self.epoch = 0
        if config.verbose >= 1:
            ratio = config.lr / previous_lr if previous_lr > 0 else float("inf")
            note = "  <- large jump, check that this is intended" if ratio > 10 else ""
            print(f"New stage: targets={config.targets}, lr {previous_lr:.3e} -> {config.lr:.3e} (x{ratio:.1f}){note}")

    def train_stages(self, stages: Sequence[TrainConfig]) -> TrainResult:
        """Trains the model through several stages, one after another.

        Every stage is an ordinary training run described by its own config, applied to the model left by the previous
        one - so a recipe like "pretrain on random walks, then fine-tune on Bellman targets with a lower learning
        rate" is a list of two configs. The whole recipe is data, which makes runs reproducible and comparable.

        Weights and their EMA copy carry over between stages; see :meth:`set_stage` for what does not, and for the
        jump of the learning rate that a boundary implies.

        Example:

        >>> from cayleypy import CayleyGraph, PermutationGroups
        >>> from cayleypy.models import ModelConfig
        >>> from cayleypy.train import TrainConfig, Trainer
        >>> graph = CayleyGraph(PermutationGroups.lrx(4), device="cpu")
        >>> model_config = ModelConfig(model_type="MLP", input_size=4, num_classes_for_one_hot=4, layers_sizes=[16])
        >>> common = dict(n_walks=8, rw_length=4, batch_size=16, seed=0)
        >>> stages = [
        ...     TrainConfig(n_epochs=2, **common),
        ...     TrainConfig(n_epochs=1, targets="bellman", lr=1e-4, **common),
        ... ]
        >>> result = Trainer(graph, model_config, stages[0]).train_stages(stages)
        >>> [len(stage) for stage in result.stage_losses]
        [2, 1]

        :param stages: Configuration of every stage, in order. Must be non-empty. Passing the config the trainer was
            created with as the first stage is not double work - that stage is entered already, and it is not set up
            again.
        :return: Result of training, with the loss curve of the whole run and its split by stage.
        """
        if len(stages) == 0:
            raise ValueError("At least one stage is needed.")
        stage_losses = []
        for index, config in enumerate(stages):
            # The documented flow passes the config the trainer was created with as the first stage. Entering it again
            # would rebuild the data source that __init__ has just built, and building one runs a breadth-first search
            # when the stage uses anchors - so a large anchor table would be computed twice and held twice at once.
            already_entered = index == 0 and config is self.config and self.epoch == 0
            if not already_entered:
                self.set_stage(config)
            stage_losses.append(self.train().losses)
        return TrainResult(
            losses=[loss for stage in stage_losses for loss in stage],
            n_steps=self.n_steps,
            stage_losses=stage_losses,
        )

    def predictor(self, use_ema: bool = True) -> Predictor:
        """Creates predictor using the trained model, e.g. to pass it to beam search.

        :param use_ema: Whether to use the EMA copy of the weights (if it is maintained) rather than the weights
            themselves. Defaults to True.
        :return: The predictor.
        """
        return Predictor(self.graph, self.model_for_inference(use_ema))

    def save(self, path: PathType, use_ema: bool = True) -> ModelConfig:
        """Saves the trained model as a self-describing checkpoint.

        The checkpoint also remembers which graph the model was trained for, so loading it for another graph fails
        instead of silently producing nonsense.

        :param path: Path to the file to write.
        :param use_ema: Whether to save the EMA copy of the weights (if it is maintained) rather than the weights
            themselves. Defaults to True.
        :return: Config stored in the checkpoint (it is `model_config` with the hash of the graph filled in).
        """
        return save_checkpoint(path, self.model_for_inference(use_ema), self.model_config, self.graph.definition)

    def model_for_inference(self, use_ema: bool = True) -> nn.Module:
        """Returns the model to use for prediction - either the EMA copy of the weights, or the weights themselves.

        :param use_ema: Whether to prefer the EMA copy. If it is not maintained (`TrainConfig.ema_decay` is 0), the
            trained model is returned regardless.
        :return: The model.
        """
        if use_ema and self.ema_model is not None:
            return self.ema_model
        return self.model

    def _update_ema(self) -> None:
        """Moves the EMA copy of the weights towards the current weights."""
        if self.ema_model is None:
            return
        decay = self.config.ema_decay
        ema_state = self.ema_model.state_dict()
        with torch.no_grad():
            for key, value in self.model.state_dict().items():
                ema_value = ema_state[key]
                if ema_value.is_floating_point():
                    ema_value.mul_(decay).add_(value.detach(), alpha=1.0 - decay)
                else:
                    # Integer entries (e.g. counters of batch normalization) have no meaningful average.
                    ema_value.copy_(value)
